---
title: 'Proposal: Perfectly Practical Polling Procedure'
author: Michael
date: '2025-06-21'
slug: proposal-perfectly-practical-polling-procedure
categories: []
tags: []
---


My home of Guernsey went to the polls recently. 
We have a bit of an odd political system, and I believe we have the opportunity to make it slightly odder.

We have a "States of Deliberation" of 38 Deputies that introduce and debate on legislation. 
There's not really an executive, it's more that there's one States' committee that's sort of more important than the others, and the president of that committee is sort of more important than the other deputies.

Up until 2020 we had a district system that roughly corresponded to the parish system of local administration (a whole other story). 
Anyway, we had a referendum on Island Wide Voting: Instead of choosing ~3 out of the ~10 people standing in your constituency, we now have to pick up to 38 people out of the whole field of candidates.

In 2020 there were 119 candidates. 
In 2025 there were 82 candidates. 

This means that you have to enter the polling station equipped with your list of chosen votes, find them on the (long) piece of ballot paper and mark them off individually. 

Sure, it's not _that_ much effort, but can we make it more efficient?
Here's my proposal:

- Firstly, each candidate should be assigned a prime number.
- In the comfort of your own home you select as many candidates up to the 38 candidate limit and multiply their respective primes together to get your personal voting product (PVP).
- On polling day, you enter the polling station and instead of being tasked with filling in 38 individual circles, you simply write your PVP on a piece of paper and place it in the box. 
  In and out in under 10 seconds.
- To perform the count the officials simply multiply everyone's PVPs together to produce the Island Wide Product (IWP), a single (very large) number that encapsulates the whole island's political views, it distils the full voting preferences of all the populace into a single integer.
- Once the Island Wide Product has been calculated (and orders sent to printers to produce paper copies to be distributed to local school children), it can be decomposed into its prime factors to tease out the vote counts.
  As any primary school child knows, a composite number has a unique prime factorisation, meaning that by decomposing the Island Wide Product, we can simply count the number of times each candidate's prime was used, meaning we can fully reconstruct the vote counts.
  
I think you will agree this is a beautiful and practical vote counting method, and I hope to see it implemented in time for Guernsey's next election.
  